# Generated by Django 4.2 on 2024-01-01 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("INITIATION", "Concept Phase"),
                            ("PLANNING", "Definiton Phase"),
                            ("EXECUTION", "Execution Phase"),
                            ("CONTROL", "Control Phase"),
                            ("CLOSED", "Closed Phase"),
                        ],
                        default="INITIATION",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified_at", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100)),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Task is open"),
                            ("IN_PROGRESS", "Task is in progress"),
                            ("DONE", "Task is done"),
                            ("BLOCKED", "Task is blocked by other"),
                            ("CANCELLED", "Task is canceled"),
                        ],
                        default="OPEN",
                        max_length=11,
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("story_points", models.IntegerField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "db_table": "task",
            },
        ),
        migrations.CreateModel(
            name="TaskTimeTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projects.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "TaskTime",
                "verbose_name_plural": "TasksTime",
                "db_table": "task_time",
            },
        ),
    ]
