version: '3.8'
services:

  management-tool-db:
    image: "postgres:latest"
    ports:
      - "5440:5432"
    container_name: management-tool-db
    env_file:
      - ../.env
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: management-tool
    command: [ "postgres", "-c", "wal_level=logical" ]
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 1s
      retries: 2
    
  management-tool-app:
    build:
      context: ../
    container_name:  management-tool-app
    command: gunicorn manage_tool.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - management-tool-db
    environment:
      - SECRET_KEY=django-insecure-0wpj*gy=q@9lznlttbst!5r_up+)vo3fa^87y9zqjltd7^dmu5
      - DEBUG=True
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOST=management-tool-db
      - DB_NAME=management-tool
      - DB_PORT=5440
    